extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
env:
  browser: true
  mocha: true
  node: true
  es6: true
parserOptions:
  ecmaFeatures:
    modules: true
  ecmaVersion: 6
  sourceType: module
rules:
  strict:
    - error
    - global
  consistent-return: off
  max-len:
    - error
    - code: 80
      ignoreStrings: true
      ignoreTemplateLiterals: true
  semi:
    - error
  comma-dangle:
    - error
    - never
  no-underscore-dangle: off
  no-case-declarations: off
  no-unused-expressions: off
  no-param-reassign: off
  no-use-before-define:
    - error
    - functions: false
  no-mixed-operators :
    - error
    - allowSamePrecedence: true
  operator-linebreak:
    - error
    - before
  no-var: error
  prefer-const: error
  no-redeclare: error
  quotes:
    - error
    - single
globals:
  dat: false,
  THREE: false,
  Stats: false
